# Generated by Django 4.1.1 on 2022-10-06 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ID_familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ID_sp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.CharField(blank=True, max_length=300)),
                ('Ano', models.IntegerField(blank=True)),
                ('Estacao', models.CharField(blank=True, max_length=300)),
                ('Classe', models.CharField(blank=True, max_length=300)),
                ('Ordem', models.CharField(blank=True, max_length=300)),
                ('Genero', models.CharField(blank=True, max_length=300)),
                ('Nome_popular', models.CharField(blank=True, max_length=300)),
                ('Numero_registros', models.IntegerField(blank=True)),
                ('Metodologia', models.CharField(blank=True, max_length=300)),
                ('Ponto_amostral', models.CharField(blank=True, max_length=300)),
                ('Regiao', models.CharField(blank=True, max_length=300)),
                ('Latitude', models.IntegerField(blank=True)),
                ('Longitude', models.IntegerField(blank=True)),
                ('Altitude', models.IntegerField(blank=True)),
                ('Responsavel_tecnico', models.CharField(max_length=300)),
                ('Projeto', models.CharField(max_length=300)),
                ('Especialidade', models.CharField(max_length=300)),
                ('nome_Especie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='BD.id_sp')),
                ('nome_Familia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='BD.id_familia')),
            ],
        ),
    ]
