# Generated by Django 4.1.1 on 2022-10-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especie',
            name='nome_Especie',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='nome_Familia',
        ),
        migrations.AddField(
            model_name='especie',
            name='Especie',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='especie',
            name='Familia',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
