# Generated by Django 4.1.1 on 2022-10-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0002_remove_especie_nome_especie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='id_familia',
            old_name='nome',
            new_name='Familia',
        ),
        migrations.RenameField(
            model_name='id_sp',
            old_name='nome',
            new_name='Especie',
        ),
    ]
